# Generated by Django 5.0.6 on 2024-06-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_login_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='senha_confirmada',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
