# Generated by Django 5.0.6 on 2024-07-04 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_login_senha_confirmada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='senha_confirmada',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='login',
            name='senha',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
