# Generated by Django 5.0.6 on 2024-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_login_senha_confirmada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_atualizacao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
