# Generated by Django 5.0.7 on 2024-07-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_cliente_data_atualizacao_cliente_data_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_criacao',
            new_name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_login',
        ),
    ]
