# Generated by Django 5.0.7 on 2024-07-23 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_cliente_data_atualizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='senha',
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='data_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='login',
            name='descricao',
            field=models.CharField(default='Entrou', max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=50, unique=True),
        ),
    ]
