# Generated by Django 5.0.7 on 2024-07-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_login_email_remove_login_senha_cliente_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='senha',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
